### ISSUE TITLE
Improve consistency of Download buttons

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#102]
Suggestion:

1. Buttons that add datasets to Download Cart should be named: 

- "Add" (when in the datasets table)
- "Add all to Download Cart" (when at the bottom of a datasets table)

2. Buttons that download data right away should be named:

- "Download now"

Question:

- What's best for capitalization? Our titles are all capitalized (e.g., "Phenotypic Scores for ..."). Should the buttons be, e.g., "Download now" or "Download Now"?

**Comment by abarysh** [comment]
Also, the "Download now" and "Add all to Download Cart" should be added to the template that renders the datasets table. Currently, I think that they aren't because /phenotypes/21/ has both buttons, /conditions/4/ has only 1 ("Add all to ...") and /papers/289/ has none.

**Comment by abarysh** [comment]
Also, make sure that all Buttons are specified consistently

`<a href='...' role='button'>Download now</a>`
instead of
`<a href='...'><button>Download now</button></a>`

**Comment by vsoch** [comment]
I think for titles we should follow the paper title convention - first capital letter and then lowercase for the rest (unless proper noun, etc.). Should we change the "Phenotypic Scores" and other similar titles to follow suit, or just have this for the buttons? We've had several conversations about these button titles over emails, and I think we've tended toward that convention.

We used to have those two buttons on all pages, and the "Download all" (which you want renamed to "Download now?" is the only one that is reasonable to do because there are many datasets with >50, and the user wouldn't be able to add them all to the cart (the limit is 50). I can't find the correspondence now, but we did discuss them at one point and decided to remove them. We probably should just remove the "Add all to download cart" on the Phenotype details page to have consistency across the site. It doesn't hurt to have it since there are usually very few phenotypes, however.

It's fairly easy to add download all buttons to the different dataset tables associated with a particular object (e.g., observable datasets) but for the search we would need to serialize the ids from the table. Is this what you'd like to try, or something else?

**Comment by vsoch** [comment]
@abarysh are you sure it's best practice to use role=button? See the second response here https://stackoverflow.com/questions/26934719/do-i-need-role-button-on-a-button. That post (and the w3c docs) seem to suggest that onclick is the right way? https://www.w3docs.com/snippets/html/how-to-create-an-html-button-that-acts-like-a-link.html. I've just been doing it the "really wrong way" for years!

**Comment by abarysh** [comment]
I would be ok with the following:

1. "Download now" -- Download immediately the data you're looking at (for any given dataset or a gene)
2. "Add" -- Add a specific dataset to the Download Cart
3. "Add all" -- Add all datasets in a table to the Download Cart 

This would mean eliminating from everywhere the 4th option, which is:
- Download immediately the data for all datasets in a table [not always available: yes at /phenotypes/587/; no at /conditions/4/]

Layout:
- To make the meaning of the "Add" and "Add all" more obvious, I think the title of the corresponding column in the datasets table should be "Download Cart". And could "Add all" be aligned to that column too? See pic attached.
![Screen Shot 2020-12-23 at 9 58 55 AM](https://user-images.githubusercontent.com/11416566/103024998-c3f99980-4505-11eb-9277-2cb927648509.png)

**Comment by abarysh** [comment]
Re: buttons -- I don't think it matters whether you use `<button>` or `<a role="button">`, as long as you use just one, not both. I agree that `<button onclick='....'>` is the best way to go.

**Comment by abarysh** [comment]
Actually, at a second thought, I'm not sure about `button onclick`. I always thought that buttons should be reserved for forms. We don't have forms, we just have links that we want to look & feel like buttons. So `<a>` may also be a perfectly reasonable choice. It might not need to have `role=button`, just `class=button` (I don't remember the details of what `role` means in this case and how bootstrap uses it internally). It's worth investigating before committing to one particular choice.

**Comment by vsoch** [comment]
Gotcha! For the Add all button - is the assumption adding from the visible page or the entire table? If the latter, what about cases where N>50 (the button would never work).

**Comment by abarysh** [comment]
I think "Add all" should add all datasets from the entire table. If the number of datasets is greater than 50, then the user should get the same alert they would get if they tried to add a 51st dataset manually (I imagine a red alert, boostrap-style, appearing below "Datasets" and above the table). 

There're not many papers (<30 out of ~500) with more than 50 datasets and a similar number of conditions/phenotypes, so this won't be a common problem. And, since we need to implement the "Cart capacity exceeded" alert anyway, it seem logical to me that this button would trigger it in some cases.

The alert should say something like:

> **Download Cart capacity exceeded.**
> Your Download Cart can hold no more than 50 datasets at a time. Please consider adding fewer datasets at a time or clearing the Download Cart before adding new datasets.

What do you think?

**Comment by vsoch** [comment]
Hmm. I guess I don't like the idea of implementing a button we know will either not be able to use, or unwanted behavior (for example, let's say there are 75 datasets in the table, I already have 4 in my cart, if I click "Add all" then some subset of the table is added, some not, and I have to clear my cart and start over and make sure to check the size of each table before clicking. Are you saying that we shouldn't allow any added given that the entire set is greater than the capacity of the cart (so I don't have to start over?) But then why should we render a button on that page that we know is not usable?

**Comment by vsoch** [comment]
Also, how would you go about implementing a download all if only a subset of the datasets are known to the page, retrieved with ajax? For the different Download All views that we currently have, this is the case but we can add the button because the view is associated with another object (e.g., a specific observable datasets). I'm not sure how to generally have a button to know all the dataset ids in a table if the entire table is not rendered, and the user might change a query to change the actual content of the table.

**Comment by abarysh** [comment]
1. I'm not sure what you mean by "only a subset of the datasets are known to the page". I'm assuming we are talking about dataset tables appearing on the Paper, Condition and Phenotype detail pages. In all those cases, you do know the dataset ids for all datasets in a table, even if only one page is shown. As far as I understand, we are not planning to have "Add all" buttons on the search pages or anywhere else. Am I misunderstanding it?
2. I assumed that, when you try to add 75 datasets at a time, you get the alert and none of them are added. The alert should be triggered by a check before we start adding datasets to the cart, not after.
3. I do agree that, if a datasets table has >50 datasets or if the number of datasets in the table + the number of datasets already in the cart is > 50, we may want to deactivate the button, with a info text appearing at hovering "The Download Cart doesn't have sufficient capacity to add this many datasets". This is also true for all the "Add" buttons if you already have 50 datasets in your cart. Same logic -- if your cart is full, why are we showing any "Add" buttons if they are unusable?

**Comment by vsoch** [comment]
> I'm not sure what you mean by "only a subset of the datasets are known to the page". I'm assuming we are talking about dataset tables appearing on the Paper, Condition and Phenotype detail pages. In all those cases, you do know the dataset ids for all datasets in a table, even if only one page is shown. As far as I understand, we are not planning to have "Add all" buttons on the search pages or anywhere else. Am I misunderstanding it?

I think you originally asked to have this added to the datasets table template (and not those specific cases, but extending to them). I'm I'm incorrect and you just mean those pages (with the associated objects) we should be ok!

> I assumed that, when you try to add 75 datasets at a time, you get the alert and none of them are added. The alert should be triggered by a check before we start adding datasets to the cart, not after.

I just checked the code, and this is correct - and we do have the check!

> I do agree that, if a datasets table has >50 datasets or if the number of datasets in the table + the number of datasets already in the cart is > 50, we may want to deactivate the button, with a info text appearing at hovering "The Download Cart doesn't have sufficient capacity to add this many datasets". This is also true for all the "Add" buttons if you already have 50 datasets in your cart. Same logic -- if your cart is full, why are we showing any "Add" buttons if they are unusable?

This makes sense. I haven't disabled all add buttons for tables in this next PR but I can do it for a future one that addresses these buttons.

**Comment by vsoch** [comment]
Actually for the last point, it might be confusing for the user to see that the buttons are disabled off the bat on the page load, but if they click any add button, see the message that their cart is full, and then all the buttons are disabled, this would be more understandable. This is also more flexible an approach because it would support starting with a page that has Add enabled (when the cart has room) and then disabling all buttons when the user hits the limit. What do you think?

**Comment by abarysh** [comment]
> I think you originally asked to have this added to the datasets table template (and not those specific cases, but extending to them). I'm I'm incorrect and you just mean those pages (with the associated objects) we should be ok!

I think this is a bit confusing because I don't have a clear picture in mind of which templates are reused/extended where and how. We didn't get to clean up the datasets template folder yet, right? Currently, in that folder I see dataset_table.html, datasets_cart_table.html, datasets_server_render_table.html, datasets_table.html and I'm not sure which one is used where. But in general, I don't see any major obstacle to this.

> Actually for the last point, it might be confusing for the user to see that the buttons are disabled off the bat on the page load, but if they click any add button, see the message that their cart is full, and then all the buttons are disabled, this would be more understandable. This is also more flexible an approach because it would support starting with a page that has Add enabled (when the cart has room) and then disabling all buttons when the user hits the limit. What do you think?

I don't think it is confusing if we provide the info at hovering (as I mentioned above). I think this would be consistent with your suggestion from before: why make the user click a button if we already know it's not possible? If the cart is full, all buttons should be off (with explanation upon hovering). If the cart is not full but there's no space for the entire dataset table, then just the "Add all" button should be off (with explanation) but the individual "Add" buttons should be on.

**Comment by vsoch** [comment]
> I think this is a bit confusing because I don't have a clear picture in mind of which templates are reused/extended where and how. We didn't get to clean up the datasets template folder yet, right? Currently, in that folder I see dataset_table.html, datasets_cart_table.html, datasets_server_render_table.html, datasets_table.html and I'm not sure which one is used where. But in general, I don't see any major obstacle to this.

I can give more insight to these!

 - `datasets_server_render_table` is used across almost all views, and it replaced `datasets_table` which is essentially the same thing but just splot on the browser. The only places this older view is still used are conditionset details, and datasets tag and class (I don't even think class is exposed anywhere obviously, it might be one of those views to entirely remove).
 -  `datasets_table` is the older view of the table mentioned above.
 - `datasets_cart_table` is a version of the `datasets_server_render_table` that reloads the page to remove datasets instead of doing an ajax call. The reason is because when the user removes the dataset, if we don't refresh the page the session doesn't update (it's technically changed on the server but this doesn't update the page that is already loaded) so the (should be removed) dataset is downloaded.

> I don't think it is confusing if we provide the info at hovering (as I mentioned above). I think this would be consistent with your suggestion from before: why make the user click a button if we already know it's not possible? If the cart is full, all buttons should be off (with explanation upon hovering). If the cart is not full but there's no space for the entire dataset table, then just the "Add all" button should be off (with explanation) but the individual "Add" buttons should be on.

Ok that's reasonable, and we should still disable buttons that are previously working given that it gets full during an interaction (this is done for the current PR). I can add this update to make them disabled on page load for a future one.
