### ISSUE TITLE
Paper download zips?

### ISSUE THREAD

**Issue by vsoch** [yeastphenome/yeastphenome.org#59]
Hey @abarysh I'm investigating the previous URLs, and I found that we should have one that allows for download a zip of a paper. It looks like we don't have this `DATA_DIR` (as defined in settings) or any of these files. Here is the relevant function:

```python
@ratelimit(key="ip", rate=rl_rate, block=rl_block)
def download_zip(request, paper_id, paper_pmid):

    p = get_object_or_404(Paper, pk=paper_id)

    # Check data & tested strains permission status
    permissions_data = list(
        set(p.dataset_set.all().values_list("data_source__release", flat=True))
    )
    permissions_tested = list(
        set(p.dataset_set.all().values_list("tested_source__release", flat=True))
    )

    if all(permissions_data) & all(permissions_tested):
        file_name = os.path.join(settings.DATA_DIR, "%d.zip" % p.pmid)
    else:
        file_name = os.path.join(settings.DATA_DIR, "na.zip")

    file_path = os.path.join(settings.STATIC_ROOT, file_name)

    response = HttpResponse(open(file_path, "rb"), content_type="application/zip")
    response["Content-Disposition"] = 'attachment; filename="%s_%d.zip"' % (
        settings.DOWNLOAD_PREFIX,
        p.pmid,
    )
    return response
```
I think there are a few options:
 - Restore files exactly as they are now, including the na.zip
 - Generate a single na.zip to return in all cases with some README about how to retrieve the file (GitHub?) 
 - Disable the paper zip download entirely
 - Some method to direct the user to another download source.

**Comment by abarysh** [comment]
I say option 3 -- disable the paper zip download entirely. In the last round of comments I sent (Nov 12), I had this in the Papers section:
- papers/198: instead of the "Download paper package" button, we should add one more row to the table above. Right after "Citation" I would add a row like this:
	- Raw data & curation code
	- <link to github>
The yeastphenome-data repo is private for now (but we'll eventually flip the switch when we're ready).

This change will address this issue and make download_zip unnecessary.

For context: this function download the yeastphenome-data folder for a specific paper. Once we provide the link to github, this function is not needed.

**Comment by vsoch** [comment]
Ah gotcha! I haven’t looked at that email yet, but soon!

**Comment by vsoch** [comment]
The GitHub link is added, and paper download zip is removed, closing issue (work in #58).
