### ISSUE TITLE
Data download format, efficiency, and messages

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#76]
The format of the dataframe - right now it's a flattened version with gene ids over names, and I remember you had wanted a matrix of dataset ids by genes. I remember testing this a while back, and it was immensely slow to use the old method (at least when we add more datasets) so likely this needs to be looked at again.

**Comment by abarysh** [comment]
Related to this: /genes/3335/ The download all button for genes still downloads a list of datasets (e.g., meaning papers and metadata) and not scores.

**Comment by vsoch** [comment]
Yeah it uses the same function on the backend so this makes sense, if we fix that function we fix both!

**Comment by vsoch** [comment]
This was also fixed! I tested downloading 2, 5, and 50, however since the page doesn't reload and we use messages, there isn't a clear message to the user about the 50 limit (the box seems to just stop working) and then when we change pages we see where they all went!

![image](https://user-images.githubusercontent.com/814322/101989707-9851f600-3c5f-11eb-87a1-05b695f9d4fc.png)

We would want this to show immediately on the page in question.

**Comment by abarysh** [comment]
Yes, I guess we can move this into a new issue: Provide immediate feedback to user when they try to add dataset above quota. But I don't think it has to be done by official_release1 milestone.
PS: there seems to be a typo in this message: it should be "which will go over the 50 limit" (not 500).

**Comment by vsoch** [comment]
Ah good catch! I changed it to be a variable and forgot to change it in the string, I can quickly fix in this PR.

**Comment by abarysh** [comment]
All questions were either addressed or moved to new issues.
