### ISSUE TITLE
Filtering on the gene phenotypic scores page doesn't work

### ISSUE THREAD

**Issue by abarysh** [yeastphenome/yeastphenome.org#90]
E.g.: /genes/3335/scores/ -- whatever you type in the "Filter" box, the table doesn't get filtered.

**Comment by abarysh** [comment]
For comparison: /genes/3335/similar/ -- the filtering works as expected.

**Comment by vsoch** [comment]
I accidentally removed the filter (which is there for production) https://github.com/yeastphenome/yeastphenome.org/blob/master/yeastphenome/apps/api/datasets.py#L357 when we refactored all the backend views to not redundantly do it. This one is different because it doesn't use the shared function, so it shouldn't have been removed.

**Comment by vsoch** [comment]
okay the fix to get the name and normalized value is a quick fix, but we can't do the same for the ranks column because it's calculated on the fly (separated from what we have in the database). @abarysh have you ever successfully annotated a model with some kind of calculation? I found Sum and Count, but that doesn't seem to be exactly what we would want.

**Comment by abarysh** [comment]
I think filtering on gene names is sufficient for now.

**Comment by vsoch** [comment]
You mean dataset names right? If so, sounds good! I'll test what I have and update the PR soon.

**Comment by abarysh** [comment]
Yep sorry, dataset names

**Comment by vsoch** [comment]
This is fixed, we can search by name. Sometimes it seems a little slow, but we can open an issue later if it stands out again.
